### ISSUE TITLE
Homepage and/or sources URL missing in the RubyGems release

### ISSUE THREAD

**Issue by mensfeld** [kojix2/ruby-minigraph#1]
Hey,

My name is Maciej Mensfeld and I run a research security project called https://diffend.io.

I've noticed, that this gem has a corresponding Github repository, yet it is indicated neither as a homepage nor as a source URL in the RubyGems release (https://rubygems.org/gems/ruby-minigraph).

Just wanted to let you know.

Have a great day

**Comment by kojix2** [comment]
Hi @mensfeld
Thank you for reporting me.

I had some trouble uploading the gem.
It seems that the Gem was broken at that time.

I think your activity will help a lot of people.
Keep up the good work!

**Comment by kojix2** [comment]
（´-`）.｡oO（Hmmm. It's not an upload problem. I don't know why this is happening. Anyway, I'll fix it.)

**Comment by mensfeld** [comment]
@kojix2 thanks. Since you've removed this gem from rubygems I will close this issue.
